version: "3"
services:
     web:
         image: 'gitlab/gitlab-ce:latest'
         hostname: 'gitlab.selit.ru'
         environment:
             GITLAB_OMNIBUS_CONFIG: |
                 external_url 'https://gitlab.selit.ru'
                 registry_external_url 'https://gitlab.selit.ru:4567'
                 nginx['redirect_http_to_https'] = true
                 # Add any other gitlab.rb configuration here, each on its own line
         ports:
            - '80:80'
            - '443:443'
            - '22:22'
            - '4567:4567'
         volumes:
            - 'gitlab_config:/etc/gitlab'
            - 'gitlab_logs:/var/log/gitlab'
            - 'gitlab_data:/var/opt/gitlab'

volumes:
    gitlab_config:
    gitlab_logs:
    gitlab_data:

